In [8]:
import pandas as pd
import numpy as np
from baseball_scraper.baseball_reference import TeamScraper

In [ ]:
s = TeamScraper()
s.set_season(2023)
data = s.scrape('NYY')
data.head()

        Date   Tm Home_Away  Opp  ... Attendance  cLI  Streak  Orig. Scheduled
1 2023-03-30  NYY      Home  SFG  ...    46172.0  .93       1             None
2 2023-04-01  NYY      Home  SFG  ...    41642.0  .92      -1             None
3 2023-04-02  NYY      Home  SFG  ...    42053.0  .89       1             None
4 2023-04-03  NYY      Home  PHI  ...    37202.0  .91       2             None
5 2023-04-04  NYY      Home  PHI  ...    35392.0  .92      -1             None

[5 rows x 20 columns]