In [1]:
import pandas as pd
import numpy as np
import baseball_scraper.baseball_reference as bsr
from helpers import get_teams
import time
import os

In [2]:
teams = get_teams.get_team_names('mlb')

['MIN', 'PIT', 'TBA', 'CHN', 'DET', 'MIA', 'OAK', 'SEA', 'WAS', 'BAL', 'CLE', 'ANA', 'NYN', 'SDN', 'TEX', 'ARI', 'CHW', 'HOU', 'MIL', 'PHI', 'SLN', 'BOS', 'COL', 'LAN', 'NYA', 'SFN', 'TOR', 'ATL', 'CIN', 'KCA']

In [15]:
teams = get_teams.get_team_names('mlb')

s = bsr.TeamScraper()
s.set_season(2023)
i = 0
for x in teams:
    if i == 0:
        results = s.scrape(x)
        print(f'{i+1}')
        i+=1
    elif i > 0 and i % 4 != 0:
        new = s.scrape(x)
        results = pd.concat([results,new],ignore_index=True)
        i+=1
    else:
        time.sleep(7*60)
        results = pd.concat([results,new],ignore_index=True)
        print(f'{i+1}')
        i+=1

path = os.path.join(os.curdir,'data')
results.to_csv(f'{path}/mlb_stats.csv')

1
5
9

ValueError: Data cannot be retrieved for this team/year combo. Please verify that your team abbreviation is accurate and that the team existed during the season you are searching for. Team=ANA; Year=2023

In [14]:
x = pd.read_csv(f'{path}mlb_stats.csv')
display(x)

,Unnamed: 0,Date,Tm,Home_Away,Opp,W/L,R,RA,Inn,W-L,...,GB,Win,Loss,Save,Time,D/N,Attendance,cLI,Streak,Orig. Scheduled
0,0,2023-03-30,MIN,@,KCR,W,2.0,0.0,9.0,1-0,...,Tied,López,Greinke,Duran,2:32,D,38351.0,1.01,1,NaN
1,1,2023-04-01,MIN,@,KCR,W,2.0,0.0,9.0,2-0,...,up 0.5,Gray,Lyles,López,2:18,D,16633.0,1.06,2,NaN
2,2,2023-04-02,MIN,@,KCR,W,7.0,4.0,9.0,3-0,...,up 0.5,Ryan,Keller,NaN,2:35,D,14589.0,1.07,3,NaN
3,3,2023-04-03,MIN,@,MIA,W,11.0,1.0,9.0,4-0,...,up 0.5,Mahle,Cueto,NaN,2:31,N,8898.0,0.99,4,NaN
4,4,2023-04-04,MIN,@,MIA,L,0.0,1.0,9.0,4-1,...,up 0.5,Alcantara,Maeda,NaN,1:57,N,10668.0,1.07,-1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,643,2023-09-27,CHC,@,ATL,L-wo,5.0,6.0,10.0,82-76,...,7.0,Chavez,Palencia,NaN,2:51,N,37246.0,2.52,-2,NaN
644,644,2023-09-28,CHC,@,ATL,L,3.0,5.0,9.0,82-77,...,8.0,Wright,Stroman,Iglesias,2:43,N,40249.0,2.47,-3,NaN
645,645,2023-09-29,CHC,@,MIL,L-wo,3.0,4.0,10.0,82-78,...,9.0,Boushley,Cuas,NaN,3:03,N,39216.0,2.77,-4,NaN
646,646,2023-09-30,CHC,@,MIL,W,10.0,6.0,9.0,83-78,...,8.0,Wesneski,Lauer,Taillon,3:02,N,42652.0,0.94,1,NaN
647,647,2023-10-01,CHC,@,MIL,L,0.0,4.0,9.0,83-79,...,9.0,Houser,Smyly,NaN,2:23,D,42946.0,0.00,-1,NaN

AssertionError: